include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # General Rules
    avoid_print: true
    await_only_futures: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_constructor_bodies: true
    file_names: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_is_not_empty: true
    type_init_formals: true
    unnecessary_const: true
    unnecessary_new: true

    # Riverpod specific rules
    avoid_redundant_argument_values: true
    prefer_const_constructors_in_immutables: true
    unnecessary_lambdas: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  language:
    strict-casts: true
    strict-raw-types: true
