name: test_exercise
description: Private project to show Software development capabilities
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.0-nullsafety.2
  dio: 5.4.0
  equatable: 2.0.5
  flutter_bloc: 8.1.3
  get_it: 7.2.0
  go_router: 13.0.0

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0

flutter:
  uses-material-design: true
