name: test_exercise
description: Private project to show Software development capabilities
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: 0.10.0-nullsafety.2
  dio: 5.4.0
  equatable: 2.0.5
  flutter_bloc: 8.1.3
  get_it: 7.2.0
  go_router: 13.0.0
  cupertino_icons: 1.0.2
  dynamic_color: ^1.6.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_rename_plus: ^1.0.1

  flutter_lints: 2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
